
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
    environment:
      - CURRENT_STAGE=2
      - USE_STATIC_DASHBOARD=false
      - NODE_ENV=production
      - AWS_ENDPOINT_URL=http:/midominio.local
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    expose:
      - "3000"
    restart: unless-stopped
