apiVersion: v1
kind: ConfigMap
metadata:
  name: seed-config
  namespace: localstack
data:
  .env: |
    AWS_ACCESS_KEY_ID=test
    AWS_SECRET_ACCESS_KEY=test
    AWS_DEFAULT_REGION=eu-west-1
    S3_STATE_BUCKET=la-huella-remote-state

  seed.sh: |
    #!/usr/bin/env bash
    set -euo pipefail
    ENDPOINT="http://localstack.localstack:4566"

    echo "==> Checking/creating bucket: ${S3_STATE_BUCKET} in ${AWS_DEFAULT_REGION}"

    # Si ya existe, OK; si no, lo crea con region explícita
    if aws --endpoint-url="$ENDPOINT" s3api head-bucket --bucket "$S3_STATE_BUCKET" 2>/dev/null; then
      echo "Bucket ${S3_STATE_BUCKET} already exists ✅"
    else
      aws --endpoint-url="$ENDPOINT" s3api create-bucket \
        --bucket "$S3_STATE_BUCKET" \
        --create-bucket-configuration LocationConstraint="${AWS_DEFAULT_REGION}" || true
      echo "Bucket ${S3_STATE_BUCKET} created ✅"
    fi

    echo "✅ Seed minimal completed (S3 state ready)"
