apiVersion: v1
kind: ConfigMap
metadata:
  name: seed-config
  namespace: localstack
data:
  .env: |
    AWS_ACCESS_KEY_ID=test
    AWS_SECRET_ACCESS_KEY=test
    AWS_DEFAULT_REGION=eu-west-1

    S3_STATE_BUCKET=la-huella-remote-state

  seed.sh: |
    #!/usr/bin/env bash
    set -euo pipefail

    # DNS interno del Service en K8s
    ENDPOINT="http://localstack.localstack:4566"

    # nombre del bucket de estado
    STATE_BUCKET="${S3_STATE_BUCKET:-lahuella-tf}"

    echo "==> comprobando/creando bucket de estado: ${STATE_BUCKET}"

    # Si existe, OK; si no, lo crea
    if aws --endpoint-url="$ENDPOINT" s3api head-bucket --bucket "$STATE_BUCKET" 2>/dev/null; then
      echo "Bucket ${STATE_BUCKET} ya existe ✅"
    else
      aws --endpoint-url="$ENDPOINT" s3api create-bucket --bucket "$STATE_BUCKET"
      echo "Bucket ${STATE_BUCKET} creado ✅"
    fi

    echo "✅ seed minimal completado (solo S3 estado)"

