apiVersion: batch/v1
kind: Job
metadata:
  name: localstack-seed
  namespace: localstack
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: seeder
          image: public.ecr.aws/aws-cli/aws-cli:latest
          command: ["/bin/sh","-c"]
          args:
            - |
              echo "Starting Localstack seed job..."
              set -euo pipefail
              set -a; . /config/.env; set +a

              echo "Checking Localstack health endpoint..."
              for i in {1..10}; do
                if curl -s http://localstack.localstack:4566/_localstack/health | grep -q '"running"'; then
                  echo "✅ Localstack is healthy."
                  break
                fi
                echo "⏳ Attempt $i/10: Localstack not ready yet..."
                sleep 5
              done

              echo "Verifying or creating S3 state bucket: $S3_STATE_BUCKET ..."
              if aws --endpoint-url=http://localstack.localstack:4566 s3api head-bucket --bucket "$S3_STATE_BUCKET" 2>/dev/null; then
                echo "✅ Bucket '$S3_STATE_BUCKET' already exists."
              else
                aws --endpoint-url=http://localstack.localstack:4566 s3api create-bucket --bucket "$S3_STATE_BUCKET"
                echo "✅ Bucket '$S3_STATE_BUCKET' created successfully."
              fi

              echo "Seed job completed successfully!"
          volumeMounts:
            - name: seed-config
              mountPath: /config
      volumes:
        - name: seed-config
          configMap:
            name: seed-config
            defaultMode: 0555
            items:
              - key: .env
                path: .env
              - key: seed.sh
                path: seed.sh

